# Generated by Django 4.2 on 2026-06-07 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="enrollment",
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="module",
            name="course",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="course",
            name="preview_video_url",
        ),
        migrations.RemoveField(
            model_name="course",
            name="short_description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="is_preview",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="module",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="user",
            name="completed_courses_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="total_learning_hours",
        ),
        migrations.AddField(
            model_name="course",
            name="currency",
            field=models.CharField(default="XAF", max_length=10),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="core.course",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="LessonProgress",
        ),
        migrations.DeleteModel(
            name="Module",
        ),
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.course"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
