# Generated by Django 4.2 on 2026-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_payment_alter_lessonprogress_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=6)),
                ("purpose", models.CharField(default="registration", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Code de vérification",
                "verbose_name_plural": "Codes de vérification",
                "ordering": ["-created_at"],
            },
        ),
    ]
